### ISSUE TITLE
Parameter typing expansion

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/queenbee#43]
This issue is a mix of RFI/design discussion to determine whether we should add more types to parameter values.

I have encountered this issue while testing queenbee workflows against the current schema. I was thinking of setting up a dag task loop based off of a workflow level variable and realised that parameter values cannot be lists or objects.

```yaml
type: workflow
name: flow-loop-reference

inputs:
  parameters:
  - name: loop-array
    value: ['stuff', 'things']

operators:
- type: operator
  name: test
  image: test

templates:
- type: function
  name: test-template
  operator: test
  command: echo {{inputs.parameters.foo}}
  inputs:
    parameters:
      - name: foo
        value: bar

flow:
  name: flow-incorrect-loop-reference
  tasks:
  - name: test
    template: test-template
    arguments:
      parameters:
      - name: foo
        value: '{{item}}'
    loop: '{{workflow.inputs.parameters.loop-array}}'
```
