### ISSUE TITLE
Add `loop control` key

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/queenbee#87]
When running a looped task it will be useful to indicate some form of `loop control` key (much like [Ansible](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#tracking-progress-through-a-loop-with-index-var)).

The `key` will be used to distinguish between artifacts being aggregated by another task. The `sub_folder` can be used to persist the artifacts in a specific 

Roughly the loop control will look something like this inside the task template:

```yaml
loop:
  from:
     type: tasks
     name: split-grid
     variable: grid-list
  control:
    key:  '{{item.name}}-{{item.foo}}-{{item.bar}}'
```

The understanding is that when another task `aggregates` a specific artifact for the loop it will be saved in a folder using this format:

```
                workdir
                ├── path/to/non-aggregated-artifact
                 └── path/to/aggregated-artifact
                    ├── <loop-control-key-1>
                    ├── <loop-control-key-2>
                    ├── ...
                    └── <loop-control-key-x>
```

**important**: Note that we are not proposing to provide a file type at the end of the loop key (unless it is templated at part of the loop key)

Here is a full example of an loop being aggregated by another task.
```yaml
- name: daylight-factor-simulation
  template: honeybee-radiance/ray-tracing
  dependencies:
  - split-grid
  - create-octree
  loop:
    from:
      type: tasks
      name: split-grid
      variable: grid-list
    control:
      key:  '{{item.name}}-{{item.foo}}-{{item.bar}}'
  arguments:
    parameters:
    - name: radiance-parameters
      from:
        type: inputs
        variable: radiance-parameters
    artifacts:
    - name: grid
      from:
        type: tasks
        name: split-grid
        variable: output-grids-folder
      subpath: '{{item.path}}'
    - name: scene-file
      from:
        type: tasks
        name: create-octree
        variable: scene-file
  outputs:
    artifacts:
    - name: result-file
      path: 'output/raw/{{item.name}}.res'
    - name: other-result
      path: 'output/{{item.foo}}/{{item.bar}}.res'

- name: post-process
  template: honeybee-radiance/post-process
  dependencies:
  - daylight-factor-simulation
  arguments:
    artifacts:
    - name: raw-results-folder
      from:
        type: tasks
        name: daylight-factor-simulation
        variable: result-file
```

In the case above, the folder inside the `post-process` task will look something like this:

```
                workdir
                 └── raw-results-folder
                    ├── <name-1>-<foo-1>-<bar-1>
                    ├── <name-2>-<foo-2>-<bar-2>
                    ├── ...
                    └── <name-x>-<foo-x>-<bar-x>
```
